# Generated by Django 6.0.6 on 2026-06-28 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address_line_1', models.CharField(max_length=200)),
                ('postcode', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Herd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herds', to='herd.farm')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('sheep', 'Sheep'), ('cattle', 'Cattle'), ('pig', 'Pig')], max_length=20)),
                ('farm_id', models.CharField(max_length=100)),
                ('herd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='herd.herd')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('measured_at', models.DateTimeField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='herd.animal')),
            ],
        ),
        migrations.CreateModel(
            name='Pasture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastures', to='herd.farm')),
                ('herds', models.ManyToManyField(blank=True, related_name='pastures', to='herd.herd')),
            ],
        ),
    ]
