# Generated by Django 6.0.6 on 2026-07-03 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herd', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='farm_id',
            new_name='animal_id',
        ),
    ]
