# Generated by Django 6.0.6 on 2026-07-06 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('herd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='farmmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farm',
            name='users',
            field=models.ManyToManyField(related_name='farms', through='herd.FarmMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='herd',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='herds', to='herd.farm'),
        ),
        migrations.AddField(
            model_name='animal',
            name='herd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animals', to='herd.herd'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='animal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='herd.animal'),
        ),
        migrations.AddField(
            model_name='pasture',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pastures', to='herd.farm'),
        ),
        migrations.AddField(
            model_name='pasture',
            name='herds',
            field=models.ManyToManyField(blank=True, related_name='pastures', to='herd.herd'),
        ),
        migrations.AddConstraint(
            model_name='farmmembership',
            constraint=models.UniqueConstraint(fields=('farm', 'user'), name='unique_farm_membership'),
        ),
    ]
