# Generated by Django 6.0.6 on 2026-07-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herd', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pasture',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
