# Generated by Django 6.0.6 on 2026-07-08 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herd', '0003_pasture_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='herd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animals', to='herd.herd'),
        ),
    ]
